version: "3"

services:
  andcool_site_v4:
    container_name: andcool_site_v4
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - nginx

networks:
  nginx:
    external: true
    name: nginx
